### ISSUE TITLE
Populating With Stored Content

### ISSUE THREAD

**Issue by louisjjs** [hanhdt/vue-trix#10]
How do we populate html data like from database ?

**Comment by hanhdt** [comment]
Please, refer to doc [here](https://github.com/basecamp/trix#populating-with-stored-content).
In case of Vue, you just need to initial load html data from database into the `data` option of your component, then use `v-model` bind to the data option.

You may want to check [sample code](https://github.com/hanhdt/vue-trix/blob/master/example/src/components/Editor.vue)

**Comment by hanhdt** [comment]
Can you show codes for your actual situation?
Btw, in Vue.js, you can *watch* field that you assigned data to v-model directive.

**Comment by joaoprado** [comment]
Sorry i totally forgot about this.

So, I set my component v-model directive as this and when the data property is changed after the component is loaded, it doesn't change the content inside the component.

I "fixed" by setting a `pageIsLoaded` property in my component and use `v-if` to show the text editor only after i have all the data i need.
