### ISSUE TITLE
How to set the attachment’s URL attribute.

### ISSUE THREAD

**Issue by LiangWei88** [hanhdt/vue-trix#108]
I know how to upload a file remotely ,
but how to set the attachment’s URL attribute??
just attachement.url = "xxx"???

**Comment by hanhdt** [comment]
Hi,

In order to set the attachment's URL, you can do something like:
```
function setAttachmentURL(event) {
  var attributes = {
    url: HOST + key,
    href: HOST + key + "?content-disposition=attachment"
  };
  event.attachment.setAttributes(attributes);
}
```

**Comment by LiangWei88** [comment]
thanks very much
I choice another plugin 
cause of this plus add an caption under img
and I cannot remove it ^_^
but beside that, this plugin is great
thank you

**Comment by abrhambas01** [comment]
How do I get the attachment's url after removing it? like it's url ?
