### ISSUE TITLE
Different h sizes

### ISSUE THREAD

**Issue by gustawdaniel** [hanhdt/vue-trix#11]
How to select between `h1`, `h2`, ... `h6`?

**Comment by hanhdt** [comment]
As Trix editor support by default, you can just work with attributes `bold`, `italic`, `href`, and `strike`, and the block-level attributes `heading1`, `quote`, `code`, `bullet`, and `number`
So, for now the heading is just one level.
You can look at here: https://github.com/basecamp/trix#working-with-attributes-and-nesting
