### ISSUE TITLE
DisabledEditor not working?

### ISSUE THREAD

**Issue by mickenorlen** [hanhdt/vue-trix#116]
Hi,

Thanks for a great package!

I've tried setting the disabledEditor prop in many different ways but it doesn't have any effect.

:disabledEditor="true"
disabledEditor="true"
disabledEditor
disabled-editor=...
...

Whats the syntax or could it be some bug?

**Comment by hanhdt** [comment]
Hi @mickenorlen ,

Could you try with following:
```
...
<VueTrix
    input-id="feAppDescription"
    v-model="description"
    :disabled-editor="true"
/>
...
```

**Comment by hanhdt** [comment]
I assumed that you already resolved this. Please, feel free to open again if it's still issue.
