### ISSUE TITLE
I am getting error 'window is not defined' when page refreshes

### ISSUE THREAD

**Issue by kudapara** [hanhdt/vue-trix#12]
Hi

I have a ```Nuxt``` projext and I have included ```vue-trix```.
It works perfectly however when a user refreshes the page it shows and error 'window is not defined'.
I have attached a picture with the error.

How do I fix this error?
![image](https://user-images.githubusercontent.com/13519184/51046797-b4f6d680-15cf-11e9-8ab5-9311cf0e2744.png)

**Comment by hanhdt** [comment]
Hi,

Which `vue-trix` version you are working on?

**Comment by kudapara** [comment]
Thanks, it was the server side rendering issue. I ended up using it as a plugin and setting ```ssr``` to false in the ```nuxt.confug.js``` file

**Comment by atymic** [comment]
@kudapara 

Can you share how you implemented it?
I've had a go at creating it as a plugin but it doesn't seem to work correctly as I can't access the component.

Thanks!
