### ISSUE TITLE
problem with v1.1.3 on wards - Can't resolve 'vue-runtime-helpers'

### ISSUE THREAD

**Issue by estani** [hanhdt/vue-trix#121]
After an update to 1.1.5 (from 1.1.2) I got the following error when starting up webpack-dev
```
ERROR in ./node_modules/vue-trix/dist/vue-trix.esm.js
Module not found: Error: Can't resolve 'vue-runtime-helpers' in '../node_modules/vue-trix/dist'
```
I tried with 1.1.4 and 1.1.3 and got the same messages, going back to 1.1.2 looks fine though.

I can't find anything in the docs pointing to some breaking changes or new dependencies.

The full Stacktrace looks like this:
```
 @ ./node_modules/vue-trix/dist/vue-trix.esm.js 4:0-73 366:26-44 374:4-18
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/components/input/TextEditor.vue?vue&type=script&lang=js&
 @ ./src/components/input/TextEditor.vue?vue&type=script&lang=js&
 @ ./src/components/input/TextEditor.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/components/ShowcasePage.vue?vue&type=script&lang=js&
 @ ./src/components/ShowcasePage.vue?vue&type=script&lang=js&
 @ ./src/components/ShowcasePage.vue
 @ ./src/_helpers/router.js
 @ ./src/_helpers/index.js
 @ ./src/index.js
```
Any Idea what might be happening?

**Comment by hanhdt** [comment]
@estani Hi,
Yes, actually it's required by `rollup`. We should re-config then should stop the error from occurring.
For currently please, install that package `vue-runtime-helpers` by yourself as workaround.
