### ISSUE TITLE
"TypeError: Cannot read property 'editor' of undefined" when localStorage is true

### ISSUE THREAD

**Issue by oza75** [hanhdt/vue-trix#127]
**Steps to reproduce** 
 - ` <VueTrix :srcContent="value" @input="input" :placeholder="placeholder" localStorage/>`
 - type something in vue trix editor 
![Capture d’écran du 2019-12-21 12-33-03](https://user-images.githubusercontent.com/29458652/71306824-ad49cf80-23e5-11ea-89b8-32498f00ab18.png)

 - Reload the page 
 - You will get this error 
![Capture d’écran du 2019-12-21 12-31-36](https://user-images.githubusercontent.com/29458652/71306813-7e335e00-23e5-11ea-85d8-b53f2f77c01d.png)
 
**Version 1.1.6**

**Comment by oza75** [comment]
The problem is here  : [https://github.com/hanhdt/vue-trix/blob/master/src/components/VueTrix.vue#L128](https://github.com/hanhdt/vue-trix/blob/master/src/components/VueTrix.vue#L128)

In Vuejs created hook $refs is undefined because the component is not created yet 
so I think you should move the block that check if localStorage is true to mounted hook and put it in this.$nextTick function

**Comment by hanhdt** [comment]
Hi @oza75 ,
Good catch! and thanks for your PR.
