### ISSUE TITLE
Some bugs with nuxt.js

### ISSUE THREAD

**Issue by webistomin** [hanhdt/vue-trix#135]
Hi! I get these errors with nuxt.js:
1. Can't resolve 'vue-runtime-helpers'
2.  In Vuejs created hook $refs is undefined because the component is not created yet

I think it has already fixed in https://github.com/hanhdt/vue-trix/commit/2282765c2a873e898ecfb24c4ded05e08317538b and https://github.com/hanhdt/vue-trix/pull/128/commits/3617d52f3fe4f58f084bdd3d97b93352644ccecd.

Can you release a new version?

**Comment by hanhdt** [comment]
Hi @webistomin,

Thanks for reminding me.
I will review and release it in a new version.
