### ISSUE TITLE
[Vue warn]: Unknown custom element: <vuetrix> - did you register the component correctly? For recursive components, make sure to provide the "name" option. (found in <Root>)

### ISSUE THREAD

**Issue by loyaruarutoitsu** [hanhdt/vue-trix#14]
Hello.

First of all thank you for the great contribution merging trix with vue, perfect match.

I'm building a Ruby on Rails App with Webpacker and VueJS and Turbolinks.

However when I added vue-trix to yarn and pack it to the website I get the following error:
```
[Vue warn]: Unknown custom element: <vuetrix> - did you register the component correctly? For recursive components, make sure to provide the "name" option. (found in <Root>)
```

I got one JS-file where I import Vuetrix like so:
```
import VueTrix from "vue-trix";
Vue.use(VueTrix)
```

Then i got my slightly modified init-code because of Turbolinks:
```
document.addEventListener('turbolinks:load', () => {
    var element = document.getElementById("vue-content");
    if (element != null) {
        var app = new Vue({
            el: element,
...
            components: {
                VueTrix
            }
        })
    }
})
```

Any thoughts are much appreciated.

**Comment by hanhdt** [comment]
Hi,
Can you explain where did you use `VueTrix` component? In Single File Component (*.vue), isn't it?

**Comment by loyaruarutoitsu** [comment]
Hi, Thanks for the quick response.

I just got it to work. To further explain:

No, I havent been using it as a single file component. I'm new to vuejs and found it rather complicated the SFCs. So I just jammed everything into a file under app/javascript/packs/editor.js with the above code.

This is how it works now, file "editor.js":
```
import TurbolinksAdapter from 'vue-turbolinks'
import Vue from 'vue/dist/vue.esm'
import VueTrix from "vue-trix";
import 'vue-trix/dist/vue-trix.css'

Vue.use(VueTrix)
Vue.use(TurbolinksAdapter)

document.addEventListener('turbolinks:load', () => {
    var element = document.getElementById("vue-editor");
    if (element != null) {
        var app = new Vue({
            el: element,
...
            components: {
                'vuetrix': VueTrix
            }
        })
    }
})
```

I noticed that the JSON-Object under "components" had a attribute name attached, I found that when I surfed this site:
https://www.classandobjects.com/tutorial/using_vue_js_with_rails/

The above file is included into the page with the following in the Rails Apps Layout file:
<%= javascript_pack_tag 'editor' %>
<%= stylesheet_pack_tag 'editor %>

Probably the Readme deserves a "How to integrate into Rails" section :) But thats maybe just me because I'm new to Vuejs. I guess alot of Rails developers use Trix because its by Basecamp.

ありがとう ございました.

**Comment by hanhdt** [comment]
Yes, you're welcome and I will think of documenting for Rails especially. Thanks for your further explanations.
