### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by seanhudson** [hanhdt/vue-trix#148]
I'm trying to load the editor for use in a Nuxt project.

I've created a plugin called trixEditor.js...

```
import Vue from "vue";
import VueTrix from "vue-trix";

Vue.use(VueTrix);
```

Assigned it properly in nuxt.config.js...

```
plugins: [
    {
      src: "@/plugins/trixEditor.js",
      ssr: false,
    },
]
```

But the editor does not appear when used in components.

Looking at the plugin code, my editor VSCode warns something I'm not familiar with...

```
module "/Volumes/Samsung_T5/Sites/nest/app/nest/node_modules/vue-trix/dist/vue-trix.umd"
Could not find a declaration file for module 'vue-trix'. '/Volumes/Samsung_T5/Sites/nest/app/nest/node_modules/vue-trix/dist/vue-trix.umd.js' implicitly has an 'any' type.
  Try `npm install @types/vue-trix` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-trix';`ts(7016)
```

Any ideas what's going on here?

**Comment by hanhdt** [comment]
@seanhudson Hi,
Thanks for submitting the issue.
I have not try it on Nuxt.js and will figure it out shortly.

**Comment by seanhudson** [comment]
Thanks, it would be great to use in my new project.

**Comment by hanhdt** [comment]
@seanhudson,
Which is your Nuxt environment?
I have tested it on Nuxt v2.11.0, Node.js v12.16.1 and it's fine.
Could you double check your plugins config?

```
// plugins/vue_trix.js
import Vue from 'vue'
import VueTrix from 'vue-trix'

Vue.use(VueTrix)
```
```
// nuxt.config.js
plugins: [
    { src: '~/plugins/vue_trix', mode: 'client' }
]
```

**Comment by seanhudson** [comment]
I have Nuxt v.2.11.0 and Node.js v12.14.1.

The plugin file is the same. However, I have the following in my nuxt.config.js file:

`
plugins: [
    {
      src: "@/plugins/trixEditor.js",
      ssr: false,
    },
]
`
I think, until v2.4 of Nuxt the `ssr: false` does the same thing. Right?

**Comment by hanhdt** [comment]
So, what is the version of VueTrix you have in local? Is it latest version?

**Comment by patrickbolle** [comment]
Hi!
Same issue here. 

Nuxt v.2.11.0 - Node.JS v12.14.1
Newest version of Vue-trix via "github:hanhdt/vue-trix"

Loading library in the mode: client or ssr:false, the component does not load at all; no errors, no reference as to what is going on.

**Comment by hanhdt** [comment]
Hi,
Could you try to NPM version?
