### ISSUE TITLE
Override default config ?

### ISSUE THREAD

**Issue by dsampaolo** [hanhdt/vue-trix#16]
Hi,

I just discovered your package and it's very interesting. I'm used to Trix in Laravel Nova.

Could you please provide an example on how to override Trix default configuration ?
It would be very helpfull (for example, I need to add h2 subheadings to the toolbar)

Thank you very much !

**Comment by hanhdt** [comment]
Hi @dsampaolo,
Thanks for great question. Currently, I'm still respected Trix defaults. Hence, overriding default configurations aren't implemented yet.

If you have ideas, a PR is welcome.
Thanks.

**Comment by franciscotrillo** [comment]
Hi,

I need pretty much the same thing. I'm trying to override `Trix.config.lang` to alter the displayed texts, but It doesn't seem to work.

Is this an issue with vue-trix?

**Comment by hanhdt** [comment]
No, you can't change only Trix's config, it needs to change styling and core rendering also I thought.

**Comment by isocroft** [comment]
I think i might work on this in another PR. Let me know if anyone has ideas on this as we go along

**Comment by hanhdt** [comment]
Actually, this request take my attention. Could you give more about your ideas if you already on it?

**Comment by isocroft** [comment]
I'm still thinking through it... Will send in my thoughts once i'm through

**Comment by AndrewMast** [comment]
This seems a tad bit sloppy, but couldn't we add a `<slot>` into the VueTrix component that goes right above the `<trix-editor>`? (and then add a prop for `toolbar` if we want to create a custom toolbar...)

**Comment by hanhdt** [comment]
I think it's possible with your suggestion.

**Comment by nribeiro90** [comment]
How to work and override `Trix.config.lang`?
