### ISSUE TITLE
 Support for the old version(5.x) of Firefox 

### ISSUE THREAD

**Issue by bcsecorg** [hanhdt/vue-trix#17]
In the old version of Firefox, the editor does not modify the contents stored by the editor.
Because in Firefox 5.x, "event.srcElement" is not supported, only "event.target" is supported.

in vue-trix/src/components/VueTrix.vue#75:
    handleContentChange (event) {
      this.editorContent = event.srcElement.innerHTML
    }

"this.editorContent = event.srcElement.innerHTML" is not supported,in Firefox 5.x.

should be:
    handleContentChange (event) {      
      this.editorContent = event.srcElement.innerHTML || event.target.innerHTML
    }

**Comment by hanhdt** [comment]
Hi @bcsecorg 

Thanks for your information. You're right `Event.srcElement` is supported from [Firefox 6.2](https://developer.mozilla.org/en-US/docs/Web/API/Event/srcElement)
I will fix it soon or would you like to submit a PR?
