### ISSUE TITLE
Issue with attachment

### ISSUE THREAD

**Issue by chintanbanugaria** [hanhdt/vue-trix#19]
Hey I am having issue swith attachment. I am uploading the the attached files for the firebase storage. 
File is uploaded to the firbase storage successfully.  However in the editor its not rendering its currect url.

Here's my code 
`
handleFile(file) {
           var storageRef = fb.storage.ref();
            var imgRef = storageRef.child(file.attachment.file.name)
            console.log(imgRef);
            imgRef.put(file.attachment.file)
            .then(snapshot =>{
                snapshot.ref.getDownloadURL().then(function(downloadURL) {
                    file.attachment.attachment.fileObjectURL =  downloadURL;
                    file.attachment.attachment.previewURL =  downloadURL;
                });
            })
            return file;
        },
        handleAttachmentAdd(file) {
            console.log(file)
            var storageRef = fb.storage.ref();
            var imgRef = storageRef.child(file.attachment.file.name)
            console.log(imgRef);
            imgRef.put(file.attachment.file)
            .then(snapshot =>{
                snapshot.ref.getDownloadURL().then(function(downloadURL) {
                     file.attachment.attachment.fileObjectURL =  downloadURL;
                    file.attachment.attachment.previewURL =  downloadURL;
                });
            })
           return file;
        },
`

What has to be the next step. Do we have to return the file object ?

Thanks, 
Chintan

**Comment by hanhdt** [comment]
Hi,
Actually, no, the editor doesn't auto-populate image's url. And you don't need to return `file` object.

Rendering depends on local component's state. 
Did you get the file's url after firebase uploaded?
If true, then you need to populate editor content state of the component which you already assigned to `v-model`.

**Comment by chintanbanugaria** [comment]
Yes I do get file's url. Will update the content state then. 

Thanks,
