### ISSUE TITLE
handle @trix-file-accept event?

### ISSUE THREAD

**Issue by ouhare** [hanhdt/vue-trix#20]
Is there a way to `preventDefault` `trix-file-accept` event for preventing dropped or pasted files ?

**Comment by hanhdt** [comment]
It means you want to preventing dropped or inserted into the editor via calling `preventDefault` under a support option?

**Comment by ouhare** [comment]
I just need `trix-file-accept` event to be emitted to be able to preventDefault the event to disable drag and dropping images or files.

From the official doc:
> If you don’t want to accept dropped or pasted files, call preventDefault() on the trix-file-accept event, which Trix dispatches just before the trix-attachment-add event.

**Comment by hanhdt** [comment]
I see. Yes, it should be supported. I will implement it. 
But a PR always welcome.

Thanks.
