### ISSUE TITLE
Can not figure out how to bind attachment

### ISSUE THREAD

**Issue by joshStillerman** [hanhdt/vue-trix#22]
The documentation for responding to attached files says:

> @trix-attachment-add fires after an attachment is added to the document. You can access the Trix attachment object through the attachment property on the event. If the attachment object has a file property, you should store this file remotely and set the attachment’s URL attribute.

This event fires, I store the attachment and generate a URL.  However, I can not find where I am supposed to set the URL property.

I have 
`addAttachment(event)
`
and the event has an attachment property, which in turn has an attachment property.  I find the file reference in there, and the reference to the localhost blob image.  Given this event, once I have a new URL for the image, where do I put it?

**Comment by joshStillerman** [comment]
I did find the example that does:
`          url: HOST + key,
          href: HOST + key + "?content-disposition=attachment"
`
and modified my code to say:
`
      .finally(() => {
        event.attachment.url = imageUri,
        event.attachment.href = imageUri + '?content-disposition=attachment'
      })
`
but the text of the element still contains:
`<figure contenteditable="false" data-trix-attachment="{&quot;contentType&quot;:&quot;image/png&quot;,&quot;filename&quot;:&quot;Screen Shot 2019-03-01 at 4.29.17 PM.png&quot;,&quot;filesize&quot;:83071,&quot;height&quot;:226,&quot;width&quot;:232}" data-trix-content-type="image/png" data-trix-id="158" data-trix-attributes="{&quot;presentation&quot;:&quot;gallery&quot;}" data-trix-serialize="false" class="attachment attachment--preview attachment--png"><img src="blob:http://localhost/5a1c3f53-3676-4292-8e71-fafab2156090" data-trix-mutable="true" data-trix-serialized-attributes="{}" width="232" height="226" data-trix-store-key="imageElement/158/blob:http://localhost/5a1c3f53-3676-4292-8e71-fafab2156090/232/226"><figcaption class="attachment__caption"><span class="attachment__name">Screen Shot 2019-03-01 at 4.29.17 PM.png</span> <span class="attachment__size">81.12 KB</span></figcaption><progress class="attachment__progress" value="0" max="100" data-trix-mutable="true" data-trix-store-key="progressElement/158"></progress></figure>
`

**Comment by joshStillerman** [comment]
Resolved. 
What is needed is:
`      .finally(() => {
        event.attachment.setAttributes({
          url: imageUri,
          href: imageUri + '?content-disposition=attachment'
        })
      })
`

**Comment by hanhdt** [comment]
Hi @joshStillerman ,
Thanks for your clarification.

**Comment by LiangWei88** [comment]
omg......
may be you should point out the function in the doc
I search it for an hour...
