### ISSUE TITLE
can we have multiple localStorage for multiple inputs?

### ISSUE THREAD

**Issue by WebMedic-X** [hanhdt/vue-trix#241]
hi

it seems we can only have one localStorage for all vuetrix inputs? they all share one? 

how can we have one for each input?

thank you

**Comment by hanhdt** [comment]
Hi @WebMedic-X,
Do you have any special reason for storing data on multiple localStorage?

I think you can try store `key:value` within one `localStorage`. For instance, you have multiple vuetrix `inputId` as `key` something like:
```
{
  "input-1": "value...",
  "input-2": "value..."
}
``` 
Thanks.

**Comment by WebMedic-X** [comment]
hi @hanhdt 

thanks for looking into it

we need to have multiple localStorage for multiple inputs 

for example a page with 3 trix editors

will try out your suggestion

thank you
