### ISSUE TITLE
Vue warning thrown

### ISSUE THREAD

**Issue by eamon-clixifix** [hanhdt/vue-trix#25]
Warning given, see below:

Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "initContent"

On version 0.7.6

**Comment by hanhdt** [comment]
Hi, thanks for your checking.
I will update it.

**Comment by hanhdt** [comment]
@eamon-clixifix Hi, could you review it on new patch 0.7.7.
Thanks.

**Comment by eamon-clixifix** [comment]
@hanhdt Yes that seems to fix it, thanks for sorting that out!

**Comment by hanhdt** [comment]
Thank you!
