### ISSUE TITLE
Attachment comments put garbage in the body html

### ISSUE THREAD

**Issue by joshStillerman** [hanhdt/vue-trix#27]
I am not sure if this is a trix problem or a vue-trix problem:

When I insert an image into the editor, my attachment callback fires, and all is good.  If however I type in the caption of the picture, the editor inserts a bunch of html  which does not render.  I will attempt to attach screen shots which show the 2 cases:

Broken case (with caption)
![image](https://user-images.githubusercontent.com/7458917/54784821-1ef8b100-4bfb-11e9-91fe-d4a872455dc4.png)

Good case (without caption)
![image](https://user-images.githubusercontent.com/7458917/54784869-3d5eac80-4bfb-11e9-8e7e-d2cecba0cf1d.png)

**Comment by hanhdt** [comment]
Thanks for opening the issue.
I will try to reproduce on my side.

**Comment by hanhdt** [comment]
I already updated it in v0.8.2. Could you please review it again?
