### ISSUE TITLE
Remove node-sass as a dependency

### ISSUE THREAD

**Issue by jessegavin** [hanhdt/vue-trix#30]
Hi, thanks so much for creating this vue wrapper for Trix!

I noticed this project is using sass for the style language in the component.  However, Sass features aren't being used (there is only 1 css selector defined).

I'd like to suggest removing it because it has some large dependencies and slows down install and build times for no benefit.

**Comment by hanhdt** [comment]
Hi,
You're right. It haven't been used.
Would you like to help me remove it?

Thank you!
