### ISSUE TITLE
This dependency was not found

### ISSUE THREAD

**Issue by kucukahmet** [hanhdt/vue-trix#34]
- VueJs: 2.6.10
- vue-trix: 0.8.1

Hello everyone,
When I use in my component, I get an error.
what would be the reason?

> trix/dist/trix.css in ./node_modules/vue-trix/dist/vue-trix.esm.js

Thanks..

**Comment by hanhdt** [comment]
Hi @kucukahmet,
What is your fully error messages? Could you share it here?
Thanks.

**Comment by hanhdt** [comment]
I assume that you already got a solution then close it here.
