### ISSUE TITLE
Trying to add attachment causing loop

### ISSUE THREAD

**Issue by DRBragg** [hanhdt/vue-trix#36]
I'm having an issue where, when drag and dropping a file, the editor component goes into what appears to be an infinite loop.

I created a clone of your editor component and ran into the same issue.

I'm attaching a screenshot of my console after dropping an image file.

![Screen Shot 2019-04-25 at 3 47 32 PM](https://user-images.githubusercontent.com/26798548/56764072-df7d3180-6771-11e9-9d02-e4c98620db68.png)

I've tried it in Chrome, Firefox, and Safari. All have issues.  I've also tried versions 0.7.4, 0.7.7, and 0.8.1

**Comment by hanhdt** [comment]
Hi,
Thanks for opening the issue. 
I will reproduce and pin it for now.

**Comment by hanhdt** [comment]
I already fixed the issue in `0.8.2`.
Thanks.

**Comment by DRBragg** [comment]
Great! Thanks I'll give it a try when I have sometime to revisit

**Comment by hanhdt** [comment]
Thank you.
