### ISSUE TITLE
Editor jumping to bottom of content when typing on previous line

### ISSUE THREAD

**Issue by enkota** [hanhdt/vue-trix#37]
There seems to be a bug when using a `v-model` to output the form data. 

Demo: https://codesandbox.io/embed/pmqxw2z0nj

If you start typing on the second line after creating line-breaks, it will always jump to the end of the textarea and won't allow you to type on the second line.

This issue doesn't occur without a v-model.

Thanks!

**Comment by hanhdt** [comment]
Hi,

Thanks for reporting the bug. I already got it and will update soon.

**Comment by enkota** [comment]
Thanks @hanhdt ! 👍

**Comment by hanhdt** [comment]
I already fixed it in v0.8.2. Could you please review it again?
Thanks.

**Comment by enkota** [comment]
All fixed as per update - https://codesandbox.io/s/n015m4745j?fontsize=14 -- great work!

**Comment by hanhdt** [comment]
Thank you!
