### ISSUE TITLE
Cursor always goes to the end when I'm typing.

### ISSUE THREAD

**Issue by jimenaleom** [hanhdt/vue-trix#38]
Hi,
There is a way to avoid that the cursos always jump to the end. 
Because when I want to edit some text on the beginning of the paragraph I can write the first character and then start writing at the end of the paragraph.

Thank you.

**Comment by hanhdt** [comment]
Hi,
Are you using the latest version? If not, please update it and the issue should be resolved.

Thanks

**Comment by hanhdt** [comment]
I will close this, please open again if it's still the issue.
