### ISSUE TITLE
VueTrix not updating on model change

### ISSUE THREAD

**Issue by jsd219** [hanhdt/vue-trix#68]
I have discovered that the editor is not updating when the v-model changes. here is the HTML. 

`<VueTrix class="trix-content responsive" id="clue" :inputId="item.id" v-model="item.message" placeholder="enter your content..."/>` this is inside a loop. 

I have added `{{item.message}}` just above the editor. When I change the content from a separate source i.e. Popup. The `{{item.message}} `changes as the type changes but the editor does not.

**Comment by hanhdt** [comment]
Hi @jsd219,
This is discussing here #52. Currently you need re-init rendering `VueTrix` when `v-model` changes.

**Comment by jsd219** [comment]
How would I go about re-init?

**Comment by hanhdt** [comment]
For example, if your application used `VueRouter`, you can do something like `this.$router.go()` or `this.$router.push({//current route path})`
Another way is pure JS: `window.location.reload();`
