### ISSUE TITLE
Possible to turn off localStorage?

### ISSUE THREAD

**Issue by ryanhovland** [hanhdt/vue-trix#8]
Thanks for you work on this package!

Is it possible to not have a the input text stored in localStorage by default? Seems like odd behavior in my opinion. Maybe better to have this as an optional setting?

**Comment by hanhdt** [comment]
Can you give further details which use cases you thought it should be turned off?

**Comment by ryanhovland** [comment]
I'd argue it's never a good idea to be saving things to localStorage without the author specifically intending to. It just seems like odd behavior for a generic WYSIWYG editor. I don't believe the regular Trix library does this. Additionally, some countries around the world have very strict privacy laws in regard to cookies, etc. 

Why not at least create an option for turning it off? I'd argue to have it off by default, but that's just my opinion. Thanks for considering this request. Have a good day!

**Comment by hanhdt** [comment]
I already updated that allows localStorage as an optional setting. You can look at [here](https://github.com/hanhdt/vue-trix/commit/b0a7eadefa5fe7bbeb304dd3133a91ee22cac19e)

Thanks.
