### ISSUE TITLE
contents are wrong, adds <!--block--> elements

### ISSUE THREAD

**Issue by estani** [hanhdt/vue-trix#83]
This happens becuase the innerHTML is used instead of the value property.

For example here (I think)
https://github.com/hanhdt/vue-trix/blob/8292855ec2dbf097152d591a058ac7a92dafe013/src/components/VueTrix.vue#L144

See: https://github.com/basecamp/trix/issues/249#issuecomment-226233606

**Comment by hanhdt** [comment]
Hi,
Good catch, thanks for finding it out.
