### ISSUE TITLE
Disable File Upload

### ISSUE THREAD

**Issue by Uysim** [hanhdt/vue-trix#87]
How to hide file upload? 
There is no doc about this

**Comment by hanhdt** [comment]
Hi,
`Vue-Trix` have not provide it as a function yet. But you can do it very easy with CSS some thing like:
```
.trix-button-group--file-tools {
  visibility: hidden;
}
```

**Comment by hanhdt** [comment]
I will close the issue. If you still have questions, please feel free open it.
