### ISSUE TITLE
Getting Error on Build

### ISSUE THREAD

**Issue by schougule-c3t** [hanhdt/vue-trix#9]
Unexpected token: punc (() [./node_modules/vue-trix/dist/vue-trix.esm.js:12,0][static/js/vendor.0a45ec1851261490d5ef.js:54076,24]

**Comment by hanhdt** [comment]
I have updated ES build on latest version. Can you try it if still got error?

**Comment by DRBragg** [comment]
ERROR in static/js/2.525fbb242d3b52c8584e.js from UglifyJs
Unexpected token: punc (() [./node_modules/vue-trix/dist/vue-trix.esm.js:12,0][static/js/2.525fbb242d3b52c8584e.js:23856,24]

I'm getting the same error.  Tried 0.6.1 and 0.5.1

**Comment by hanhdt** [comment]
@DRBragg Can you try with UMD bundle then?

**Comment by DRBragg** [comment]
I'll give that a shot this weekend. I went with a different implementation for now.  Thanks.

**Comment by schougule-c3t** [comment]
@hanhdt , It is resolved with 0.6.2. Thank you. The editor is really good.
