### ISSUE TITLE
Cannot read property 'editor' of undefined

### ISSUE THREAD

**Issue by firstaml-dima** [hanhdt/vue-trix#90]
I get a show-stopper error `Cannot read property 'editor' of undefined` and it took a long time to discover the cause.

It turns out that when a component calling Vue Trix gets unloaded (because it's v-if becomes false), then the browser throws this error, since Trix is no longer there?

**Comment by hanhdt** [comment]
Thanks for reporting issue.
I will try to reproduce it and get back to you soon.

**Comment by firstaml-dima** [comment]
I wonder if it's a global event handler looking for the Trix editor in the moments after The Vue component holding it has been destroyed?

**Comment by hanhdt** [comment]
I still can't reproduce your situation. Just tried to hide a component calling `VueTrix` with `v-if` when its state become `false` after period time but got no issue in the console.

**Comment by hanhdt** [comment]
Ok, I got it. This issue happened when you are modifying content in the editor and `VueTrix` gets unloaded right there.
I will push a patch for it. Thank you.
